language: ruby
bundler_args: --without debug
script: "bundle exec rspec spec"
env:
  - CI=true
rvm:
  - 2.0
  - 2.1
  - 2.2.2
  - 2.2.7
  - jruby
  - rbx-2
gemfile:
  - Gemfile
  - Gemfile-pure
cache: bundler
sudo: false
matrix:
  allow_failures:
     - rvm: rbx-2
