language: ruby
bundler_args: --without debug
script: "bundle exec rspec spec"
before_install: 
  - 'gem update --system --conservative || (gem i "rubygems-update:~>2.7" --no-document && update_rubygems)'
  - 'gem update bundler --conservative'
env:
  - CI=true
gemfile:
  - Gemfile
  - Gemfile-pure
rvm:
  - 2.0
  - 2.1
  - 2.2.2
  - 2.2
  - 2.3
  - jruby
  - jruby-9
  - rbx-2
  - rbx-3
cache: bundler
sudo: false
matrix:
  allow_failures:
    - rvm: jruby
    - rvm: jruby-9
    - rvm: rbx-2
    - rvm: rbx-3
