language: ruby
bundler_args: --without debug
script: "bundle exec rspec spec"
env:
  - CI=true
gemfile:
  - Gemfile
  - Gemfile-pure
rvm:
  - 2.4
  - 2.5
  - 2.6
  - 2.7
  - jruby
cache: bundler
sudo: false
matrix:
  allow_failures:
    - rvm: jruby
dist: trusty
