# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rdf-rdfa}
  s.version = "0.3.0.pre"

  s.required_rubygems_version = Gem::Requirement.new("> 1.3.1") if s.respond_to? :required_rubygems_version=
  s.authors = ["Gregg Kellogg"]
  s.date = %q{2010-12-26}
  s.description = %q{    RDF::RDFa is an RDFa reader for Ruby using the RDF.rb library suite.
}
  s.email = %q{gregg@kellogg-assoc.com}
  s.extra_rdoc_files = [
    "AUTHORS",
     "CONTRIBUTORS",
     "History.rdoc",
     "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     ".yardopts",
     "AUTHORS",
     "CONTRIBUTORS",
     "History.rdoc",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "etc/basic.html",
     "etc/foaf.html",
     "etc/xhv.html",
     "example.rb",
     "lib/rdf/.gitignore",
     "lib/rdf/rdfa.rb",
     "lib/rdf/rdfa/format.rb",
     "lib/rdf/rdfa/patches/literal_hacks.rb",
     "lib/rdf/rdfa/patches/nokogiri_hacks.rb",
     "lib/rdf/rdfa/profile.rb",
     "lib/rdf/rdfa/reader.rb",
     "lib/rdf/rdfa/version.rb",
     "lib/rdf/rdfa/vocab.rb",
     "pkg/.gitignore",
     "rdf-rdfa.gemspec",
     "script/console",
     "script/parse",
     "script/tc",
     "spec/html4-manifest.yml",
     "spec/html5-manifest.yml",
     "spec/literal_spec.rb",
     "spec/matchers.rb",
     "spec/profile_spec.rb",
     "spec/rdfa_helper.rb",
     "spec/rdfa_reader_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "spec/svgtiny-manifest.yml",
     "spec/xhtml-manifest.yml"
  ]
  s.homepage = %q{http://github.com/gkellogg/rdf-rdfa}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{RDFa reader for RDF.rb.}
  s.test_files = [
    "spec/literal_spec.rb",
     "spec/matchers.rb",
     "spec/profile_spec.rb",
     "spec/rdfa_helper.rb",
     "spec/rdfa_reader_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rdf>, ["= 0.3.0.pre"])
      s.add_runtime_dependency(%q<nokogiri>, [">= 1.3.3"])
      s.add_development_dependency(%q<rspec>, [">= 2.1.0"])
      s.add_development_dependency(%q<rdf-spec>, [">= 0.2.1"])
      s.add_development_dependency(%q<rdf-rdfxml>, [">= 0.2.1"])
      s.add_development_dependency(%q<rdf-isomorphic>, [">= 0"])
      s.add_development_dependency(%q<yard>, [">= 0"])
    else
      s.add_dependency(%q<rdf>, ["= 0.3.0.pre"])
      s.add_dependency(%q<nokogiri>, [">= 1.3.3"])
      s.add_dependency(%q<rspec>, [">= 2.1.0"])
      s.add_dependency(%q<rdf-spec>, [">= 0.2.1"])
      s.add_dependency(%q<rdf-rdfxml>, [">= 0.2.1"])
      s.add_dependency(%q<rdf-isomorphic>, [">= 0"])
      s.add_dependency(%q<yard>, [">= 0"])
    end
  else
    s.add_dependency(%q<rdf>, ["= 0.3.0.pre"])
    s.add_dependency(%q<nokogiri>, [">= 1.3.3"])
    s.add_dependency(%q<rspec>, [">= 2.1.0"])
    s.add_dependency(%q<rdf-spec>, [">= 0.2.1"])
    s.add_dependency(%q<rdf-rdfxml>, [">= 0.2.1"])
    s.add_dependency(%q<rdf-isomorphic>, [">= 0"])
    s.add_dependency(%q<yard>, [">= 0"])
  end
end

