# This file is automatically generated by ./script/intern_profile
# RDFa profile for http://www.w3.org/2011/rdfa-context/html-rdfa-1.1

class RDF::RDFa::Profile
  def self.find_with_html_rdfa_1_1(uri)
    if uri.to_s == "http://www.w3.org/2011/rdfa-context/html-rdfa-1.1"
      @_html_rdfa_1_1_prof ||= RDF::RDFa::Profile.new(RDF::URI("http://www.w3.org/2011/rdfa-context/html-rdfa-1.1"), {
      })
    else
      find_without_html_rdfa_1_1(uri)
    end
  end

  class << self
    ##
    # Override find to return this profile, if matched
    alias_method :find_without_html_rdfa_1_1, :find
    alias_method :find, :find_with_html_rdfa_1_1
  end
end
