# This file is automatically generated by script/intern_vocabulary
# RDFa vocabulary for http://www.w3.org/profile/html-rdfa-1.1

profile = RDF::RDFa::Profile.new(RDF::URI("http://www.w3.org/profile/html-rdfa-1.1"), {
  :terms => {
    :alternate      => "http://www.w3.org/1999/xhtml/vocab#alternate",
    :appendix       => "http://www.w3.org/1999/xhtml/vocab#appendix",
    :bookmark       => "http://www.w3.org/1999/xhtml/vocab#bookmark",
    :chapter        => "http://www.w3.org/1999/xhtml/vocab#chapter",
    :cite           => "http://www.w3.org/1999/xhtml/vocab#cite",
    :contents       => "http://www.w3.org/1999/xhtml/vocab#contents",
    :copyright      => "http://www.w3.org/1999/xhtml/vocab#copyright",
    :first          => "http://www.w3.org/1999/xhtml/vocab#first",
    :glossary       => "http://www.w3.org/1999/xhtml/vocab#glossary",
    :help           => "http://www.w3.org/1999/xhtml/vocab#help",
    :icon           => "http://www.w3.org/1999/xhtml/vocab#icon",
    :index          => "http://www.w3.org/1999/xhtml/vocab#index",
    :itsRules       => "http://www.w3.org/1999/xhtml/vocab#itsRules",
    :last           => "http://www.w3.org/1999/xhtml/vocab#last",
    :license        => "http://www.w3.org/1999/xhtml/vocab#license",
    :meta           => "http://www.w3.org/1999/xhtml/vocab#meta",
    :next           => "http://www.w3.org/1999/xhtml/vocab#next",
    :p3pv1          => "http://www.w3.org/1999/xhtml/vocab#p3pv1",
    :prev           => "http://www.w3.org/1999/xhtml/vocab#prev",
    :role           => "http://www.w3.org/1999/xhtml/vocab#role",
    :section        => "http://www.w3.org/1999/xhtml/vocab#section",
    :start          => "http://www.w3.org/1999/xhtml/vocab#start",
    :stylesheet     => "http://www.w3.org/1999/xhtml/vocab#stylesheet",
    :subsection     => "http://www.w3.org/1999/xhtml/vocab#subsection",
    :top            => "http://www.w3.org/1999/xhtml/vocab#top",
    :transformation => "http://www.w3.org/2003/g/data-view#transformation",
    :up             => "http://www.w3.org/1999/xhtml/vocab#up",
  },
})

RDF::RDFa::Profile.cache[RDF::URI("http://www.w3.org/profile/html-rdfa-1.1")] = profile
