# This file is automatically generated by script/intern_vocabulary
# RDFa vocabulary for http://www.w3.org/profile/html-rdfa-1.1

profile = RDF::RDFa::Profile.new(RDF::URI("http://www.w3.org/profile/html-rdfa-1.1"), {
  :terms => {
    "alternate"     => nil,
    "appendix"      => nil,
    "bookmark"      => nil,
    "chapter"       => nil,
    "cite"          => nil,
    "contents"      => nil,
    "copyright"     => nil,
    "first"         => nil,
    "glossary"      => nil,
    "help"          => nil,
    "icon"          => nil,
    "index"         => nil,
    "itsRules"      => nil,
    "last"          => nil,
    "license"       => nil,
    "meta"          => nil,
    "next"          => nil,
    "p3pv1"         => nil,
    "prev"          => nil,
    "role"          => nil,
    "section"       => nil,
    "start"         => nil,
    "stylesheet"    => nil,
    "subsection"    => nil,
    "top"           => nil,
    "transformation" => nil,
    "up"            => nil,
  },
})

RDF::RDFa::Profile.cache[RDF::URI("http://www.w3.org/profile/html-rdfa-1.1")] = profile
