# This file is automatically generated by script/intern_vocabulary
# RDFa vocabulary for http://www.w3.org/profile/rdfa-1.1

profile = RDF::RDFa::Profile.new(RDF::URI("http://www.w3.org/profile/rdfa-1.1"), {
  :prefixes => {
    "bibo"     => "http://purl.org/ontology/bibo/",
    "cal"      => "http://www.w3.org/2002/12/cal/ical#",
    "cc"       => "http://creativecommons.org/ns#",
    "dbp"      => "http://dbpedia.org/property/",
    "dbp-owl"  => "http://dbpedia.org/ontology/",
    "dbr"      => "http://dbpedia.org/resource/",
    "dc"       => "http://purl.org/dc/elements/1.1/",
    "dcterms"  => "http://purl.org/dc/terms/",
    "doap"     => "http://usefulinc.com/ns/doap#",
    "foaf"     => "http://xmlns.com/foaf/0.1/",
    "geo"      => "http://www.w3.org/2003/01/geo/wgs84_pos#",
    "gr"       => "http://purl.org/goodrelations/v1#",
    "grddl"    => "http://www.w3.org/2003/g/data-view#",
    "og"       => "http://ogp.me/ns#",
    "owl"      => "http://www.w3.org/2002/07/owl#",
    "rdf"      => "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
    "rdfa"     => "http://www.w3.org/ns/rdfa#",
    "rdfs"     => "http://www.w3.org/2000/01/rdf-schema#",
    "rif"      => "http://www.w3.org/2007/rif#",
    "rss"      => "http://purl.org/rss/1.0/",
    "sd"       => "http://www.w3.org/ns/sparql-service-description#",
    "sioc"     => "http://rdfs.org/sioc/ns#",
    "skos"     => "http://www.w3.org/2004/02/skos/core#",
    "skosxl"   => "http://www.w3.org/2008/05/skos-xl#",
    "v"        => "http://rdf.data-vocabulary.org/#",
    "vcard"    => "http://www.w3.org/2006/vcard/ns#",
    "void"     => "http://rdfs.org/ns/void#",
    "wdr"      => "http://www.w3.org/2007/05/powder#",
    "wdrs"     => "http://www.w3.org/2007/05/powder-s#",
    "xhv"      => "http://www.w3.org/1999/xhtml/vocab#",
    "xml"      => "http://www.w3.org/XML/1998/namespace",
    "xmlns"    => "http://www.w3.org/2000/xmlns/",
    "xsd"      => "http://www.w3.org/2001/XMLSchema#",
  },
  :terms => {
    "describedby" => "http://www.w3.org/2007/05/powder-s#describedby",
  },
})

RDF::RDFa::Profile.cache[RDF::URI("http://www.w3.org/profile/rdfa-1.1")] = profile
