# This file is automatically generated by script/intern_vocabulary
# RDFa vocabulary for http://www.w3.org/profile/rdfa-1.1

profile = RDF::RDFa::Profile.new(RDF::URI("http://www.w3.org/profile/rdfa-1.1"), {
  :prefixes => {
    "cal"      => nil,
    "cc"       => nil,
    "dbp"      => nil,
    "dbp-owl"  => nil,
    "dbr"      => nil,
    "dc"       => nil,
    "dcterms"  => nil,
    "foaf"     => nil,
    "geo"      => nil,
    "gr"       => nil,
    "grddl"    => nil,
    "og"       => nil,
    "owl"      => nil,
    "rdf"      => nil,
    "rdfa"     => nil,
    "rdfs"     => nil,
    "rif"      => nil,
    "sd"       => nil,
    "sioc"     => nil,
    "skos"     => nil,
    "skosxl"   => nil,
    "v"        => nil,
    "vcard"    => nil,
    "void"     => nil,
    "wdr"      => nil,
    "wdrs"     => nil,
    "xhv"      => nil,
    "xml"      => nil,
    "xmlns"    => nil,
    "xsd"      => nil,
  },
  :terms => {
    "describedby" => nil,
  },
})

RDF::RDFa::Profile.cache[RDF::URI("http://www.w3.org/profile/rdfa-1.1")] = profile
