# This file is automatically generated by ./script/intern_vocabulary
# RDFa vocabulary for http://usefulinc.com/ns/doap# loaded from http://usefulinc.com/ns/doap#
require 'rdf/rdfa/expansion'

module RDF::RDFa::Expansion
  [
    RDF::Statement.new(RDF::URI('http://usefulinc.com/ns/doap#Project'), RDF::URI('http://www.w3.org/2000/01/rdf-schema#subClassOf'), RDF::URI('http://xmlns.com/wordnet/1.6/Project'), :context => RDF::URI('http://usefulinc.com/ns/doap#')),
    RDF::Statement.new(RDF::URI('http://usefulinc.com/ns/doap#Project'), RDF::URI('http://www.w3.org/2000/01/rdf-schema#subClassOf'), RDF::URI('http://xmlns.com/foaf/0.1/Project'), :context => RDF::URI('http://usefulinc.com/ns/doap#')),
    RDF::Statement.new(RDF::URI('http://usefulinc.com/ns/doap#Specification'), RDF::URI('http://www.w3.org/2000/01/rdf-schema#subClassOf'), RDF::URI('http://www.w3.org/2000/01/rdf-schema#Resource'), :context => RDF::URI('http://usefulinc.com/ns/doap#')),
    RDF::Statement.new(RDF::URI('http://usefulinc.com/ns/doap#SVNRepository'), RDF::URI('http://www.w3.org/2000/01/rdf-schema#subClassOf'), RDF::URI('http://usefulinc.com/ns/doap#Repository'), :context => RDF::URI('http://usefulinc.com/ns/doap#')),
    RDF::Statement.new(RDF::URI('http://usefulinc.com/ns/doap#BKRepository'), RDF::URI('http://www.w3.org/2000/01/rdf-schema#subClassOf'), RDF::URI('http://usefulinc.com/ns/doap#Repository'), :context => RDF::URI('http://usefulinc.com/ns/doap#')),
    RDF::Statement.new(RDF::URI('http://usefulinc.com/ns/doap#CVSRepository'), RDF::URI('http://www.w3.org/2000/01/rdf-schema#subClassOf'), RDF::URI('http://usefulinc.com/ns/doap#Repository'), :context => RDF::URI('http://usefulinc.com/ns/doap#')),
    RDF::Statement.new(RDF::URI('http://usefulinc.com/ns/doap#ArchRepository'), RDF::URI('http://www.w3.org/2000/01/rdf-schema#subClassOf'), RDF::URI('http://usefulinc.com/ns/doap#Repository'), :context => RDF::URI('http://usefulinc.com/ns/doap#')),
    RDF::Statement.new(RDF::URI('http://usefulinc.com/ns/doap#BazaarBranch'), RDF::URI('http://www.w3.org/2000/01/rdf-schema#subClassOf'), RDF::URI('http://usefulinc.com/ns/doap#Repository'), :context => RDF::URI('http://usefulinc.com/ns/doap#')),
    RDF::Statement.new(RDF::URI('http://usefulinc.com/ns/doap#GitRepository'), RDF::URI('http://www.w3.org/2000/01/rdf-schema#subClassOf'), RDF::URI('http://usefulinc.com/ns/doap#Repository'), :context => RDF::URI('http://usefulinc.com/ns/doap#')),
    RDF::Statement.new(RDF::URI('http://usefulinc.com/ns/doap#HgRepository'), RDF::URI('http://www.w3.org/2000/01/rdf-schema#subClassOf'), RDF::URI('http://usefulinc.com/ns/doap#Repository'), :context => RDF::URI('http://usefulinc.com/ns/doap#')),
    RDF::Statement.new(RDF::URI('http://usefulinc.com/ns/doap#DarcsRepository'), RDF::URI('http://www.w3.org/2000/01/rdf-schema#subClassOf'), RDF::URI('http://usefulinc.com/ns/doap#Repository'), :context => RDF::URI('http://usefulinc.com/ns/doap#')),
    RDF::Statement.new(RDF::URI('http://usefulinc.com/ns/doap#name'), RDF::URI('http://www.w3.org/2000/01/rdf-schema#subPropertyOf'), RDF::URI('http://www.w3.org/2000/01/rdf-schema#label'), :context => RDF::URI('http://usefulinc.com/ns/doap#')),
    RDF::Statement.new(RDF::URI('http://usefulinc.com/ns/doap#homepage'), RDF::URI('http://www.w3.org/2000/01/rdf-schema#subPropertyOf'), RDF::URI('http://xmlns.com/foaf/0.1/homepage'), :context => RDF::URI('http://usefulinc.com/ns/doap#')),
    RDF::Statement.new(RDF::URI('http://usefulinc.com/ns/doap#old-homepage'), RDF::URI('http://www.w3.org/2000/01/rdf-schema#subPropertyOf'), RDF::URI('http://xmlns.com/foaf/0.1/homepage'), :context => RDF::URI('http://usefulinc.com/ns/doap#')),
  ].each {|st| COOKED_VOCAB_STATEMENTS << st }
end
