# This file is automatically generated by ./script/intern_vocabulary
# RDFa vocabulary for http://rdfs.org/sioc/ns# loaded from http://rdfs.org/sioc/ns#
require 'rdf/rdfa/expansion'

module RDF::RDFa::Expansion
  [
    RDF::Statement.new(RDF::URI('http://rdfs.org/sioc/ns#Forum'), RDF::URI('http://www.w3.org/2000/01/rdf-schema#subClassOf'), RDF::URI('http://rdfs.org/sioc/ns#Container'), :context => RDF::URI('http://rdfs.org/sioc/ns#')),
    RDF::Statement.new(RDF::URI('http://rdfs.org/sioc/ns#Post'), RDF::URI('http://www.w3.org/2000/01/rdf-schema#subClassOf'), RDF::URI('http://rdfs.org/sioc/ns#Item'), :context => RDF::URI('http://rdfs.org/sioc/ns#')),
    RDF::Statement.new(RDF::URI('http://rdfs.org/sioc/ns#Post'), RDF::URI('http://www.w3.org/2000/01/rdf-schema#subClassOf'), RDF::URI('http://xmlns.com/foaf/0.1/Document'), :context => RDF::URI('http://rdfs.org/sioc/ns#')),
    RDF::Statement.new(RDF::URI('http://rdfs.org/sioc/ns#Site'), RDF::URI('http://www.w3.org/2000/01/rdf-schema#subClassOf'), RDF::URI('http://rdfs.org/sioc/ns#Space'), :context => RDF::URI('http://rdfs.org/sioc/ns#')),
    RDF::Statement.new(RDF::URI('http://rdfs.org/sioc/ns#Thread'), RDF::URI('http://www.w3.org/2000/01/rdf-schema#subClassOf'), RDF::URI('http://rdfs.org/sioc/ns#Container'), :context => RDF::URI('http://rdfs.org/sioc/ns#')),
    RDF::Statement.new(RDF::URI('http://rdfs.org/sioc/ns#UserAccount'), RDF::URI('http://www.w3.org/2000/01/rdf-schema#subClassOf'), RDF::URI('http://xmlns.com/foaf/0.1/OnlineAccount'), :context => RDF::URI('http://rdfs.org/sioc/ns#')),
    RDF::Statement.new(RDF::URI('http://rdfs.org/sioc/ns#avatar'), RDF::URI('http://www.w3.org/2000/01/rdf-schema#subPropertyOf'), RDF::URI('http://xmlns.com/foaf/0.1/depiction'), :context => RDF::URI('http://rdfs.org/sioc/ns#')),
    RDF::Statement.new(RDF::URI('http://rdfs.org/sioc/ns#has_reply'), RDF::URI('http://www.w3.org/2000/01/rdf-schema#subPropertyOf'), RDF::URI('http://rdfs.org/sioc/ns#related_to'), :context => RDF::URI('http://rdfs.org/sioc/ns#')),
    RDF::Statement.new(RDF::URI('http://rdfs.org/sioc/ns#last_activity_date'), RDF::URI('http://www.w3.org/2000/01/rdf-schema#subPropertyOf'), RDF::URI('http://purl.org/dc/terms/date'), :context => RDF::URI('http://rdfs.org/sioc/ns#')),
    RDF::Statement.new(RDF::URI('http://rdfs.org/sioc/ns#last_item_date'), RDF::URI('http://www.w3.org/2000/01/rdf-schema#subPropertyOf'), RDF::URI('http://purl.org/dc/terms/date'), :context => RDF::URI('http://rdfs.org/sioc/ns#')),
    RDF::Statement.new(RDF::URI('http://rdfs.org/sioc/ns#last_reply_date'), RDF::URI('http://www.w3.org/2000/01/rdf-schema#subPropertyOf'), RDF::URI('http://purl.org/dc/terms/date'), :context => RDF::URI('http://rdfs.org/sioc/ns#')),
    RDF::Statement.new(RDF::URI('http://rdfs.org/sioc/ns#links_to'), RDF::URI('http://www.w3.org/2000/01/rdf-schema#subPropertyOf'), RDF::URI('http://purl.org/dc/terms/references'), :context => RDF::URI('http://rdfs.org/sioc/ns#')),
    RDF::Statement.new(RDF::URI('http://rdfs.org/sioc/ns#next_version'), RDF::URI('http://www.w3.org/2000/01/rdf-schema#subPropertyOf'), RDF::URI('http://rdfs.org/sioc/ns#later_version'), :context => RDF::URI('http://rdfs.org/sioc/ns#')),
    RDF::Statement.new(RDF::URI('http://rdfs.org/sioc/ns#previous_version'), RDF::URI('http://www.w3.org/2000/01/rdf-schema#subPropertyOf'), RDF::URI('http://rdfs.org/sioc/ns#earlier_version'), :context => RDF::URI('http://rdfs.org/sioc/ns#')),
    RDF::Statement.new(RDF::URI('http://rdfs.org/sioc/ns#reply_of'), RDF::URI('http://www.w3.org/2000/01/rdf-schema#subPropertyOf'), RDF::URI('http://rdfs.org/sioc/ns#related_to'), :context => RDF::URI('http://rdfs.org/sioc/ns#')),
    RDF::Statement.new(RDF::URI('http://rdfs.org/sioc/ns#topic'), RDF::URI('http://www.w3.org/2000/01/rdf-schema#subPropertyOf'), RDF::URI('http://purl.org/dc/terms/subject'), :context => RDF::URI('http://rdfs.org/sioc/ns#')),
    RDF::Statement.new(RDF::URI('http://rdfs.org/sioc/ns#User'), RDF::URI('http://www.w3.org/2000/01/rdf-schema#subClassOf'), RDF::URI('http://xmlns.com/foaf/0.1/OnlineAccount'), :context => RDF::URI('http://rdfs.org/sioc/ns#')),
  ].each {|st| COOKED_VOCAB_STATEMENTS << st }
end
