# This file is automatically generated by ./script/intern_vocabulary
# RDFa vocabulary for http://www.w3.org/2008/05/skos-xl# loaded from http://www.w3.org/2008/05/skos-xl#
require 'rdf/rdfa/expansion'

module RDF::RDFa::Expansion
  [
    RDF::Statement.new(RDF::URI('http://www.w3.org/2008/05/skos-xl#Label'), RDF::URI('http://www.w3.org/2000/01/rdf-schema#subClassOf'), RDF::Node.new('g70249981758620'), :context => RDF::URI('http://www.w3.org/2008/05/skos-xl#')),
  ].each {|st| COOKED_VOCAB_STATEMENTS << st }
end
