# This file is automatically generated by ./script/intern_vocabulary
# RDFa vocabulary for http://rdf.data-vocabulary.org/# loaded from http://rdf.data-vocabulary.org/#
require 'rdf/rdfa/expansion'

module RDF::RDFa::Expansion
  [
    RDF::Statement.new(RDF::URI('http://rdf.data-vocabulary.org/#Person'), RDF::URI('http://www.w3.org/2000/01/rdf-schema#subClassOf'), RDF::URI('http://www.w3.org/1999/02/22-rdf-syntax-ns#Resource'), :context => RDF::URI('http://rdf.data-vocabulary.org/#')),
    RDF::Statement.new(RDF::URI('http://rdf.data-vocabulary.org/#Organization'), RDF::URI('http://www.w3.org/2000/01/rdf-schema#subClassOf'), RDF::URI('http://www.w3.org/1999/02/22-rdf-syntax-ns#Resource'), :context => RDF::URI('http://rdf.data-vocabulary.org/#')),
    RDF::Statement.new(RDF::URI('http://rdf.data-vocabulary.org/#Product'), RDF::URI('http://www.w3.org/2000/01/rdf-schema#subClassOf'), RDF::URI('http://www.w3.org/1999/02/22-rdf-syntax-ns#Resource'), :context => RDF::URI('http://rdf.data-vocabulary.org/#')),
    RDF::Statement.new(RDF::URI('http://rdf.data-vocabulary.org/#Offer'), RDF::URI('http://www.w3.org/2000/01/rdf-schema#subClassOf'), RDF::URI('http://www.w3.org/1999/02/22-rdf-syntax-ns#Resource'), :context => RDF::URI('http://rdf.data-vocabulary.org/#')),
    RDF::Statement.new(RDF::URI('http://rdf.data-vocabulary.org/#OfferAggregate'), RDF::URI('http://www.w3.org/2000/01/rdf-schema#subClassOf'), RDF::URI('http://www.w3.org/1999/02/22-rdf-syntax-ns#Resource'), :context => RDF::URI('http://rdf.data-vocabulary.org/#')),
    RDF::Statement.new(RDF::URI('http://rdf.data-vocabulary.org/#Review'), RDF::URI('http://www.w3.org/2000/01/rdf-schema#subClassOf'), RDF::URI('http://www.w3.org/1999/02/22-rdf-syntax-ns#Resource'), :context => RDF::URI('http://rdf.data-vocabulary.org/#')),
    RDF::Statement.new(RDF::URI('http://rdf.data-vocabulary.org/#Review-aggregate'), RDF::URI('http://www.w3.org/2000/01/rdf-schema#subClassOf'), RDF::URI('http://rdf.data-vocabulary.org/#Review'), :context => RDF::URI('http://rdf.data-vocabulary.org/#')),
    RDF::Statement.new(RDF::URI('http://rdf.data-vocabulary.org/#Recipe'), RDF::URI('http://www.w3.org/2000/01/rdf-schema#subClassOf'), RDF::URI('http://www.w3.org/1999/02/22-rdf-syntax-ns#Resource'), :context => RDF::URI('http://rdf.data-vocabulary.org/#')),
    RDF::Statement.new(RDF::URI('http://rdf.data-vocabulary.org/#Breadcrumb'), RDF::URI('http://www.w3.org/2000/01/rdf-schema#subClassOf'), RDF::URI('http://www.w3.org/1999/02/22-rdf-syntax-ns#Resource'), :context => RDF::URI('http://rdf.data-vocabulary.org/#')),
    RDF::Statement.new(RDF::URI('http://rdf.data-vocabulary.org/#Address'), RDF::URI('http://www.w3.org/2000/01/rdf-schema#subClassOf'), RDF::URI('http://www.w3.org/1999/02/22-rdf-syntax-ns#Resource'), :context => RDF::URI('http://rdf.data-vocabulary.org/#')),
    RDF::Statement.new(RDF::URI('http://rdf.data-vocabulary.org/#Rating'), RDF::URI('http://www.w3.org/2000/01/rdf-schema#subClassOf'), RDF::URI('http://www.w3.org/1999/02/22-rdf-syntax-ns#Resource'), :context => RDF::URI('http://rdf.data-vocabulary.org/#')),
    RDF::Statement.new(RDF::URI('http://rdf.data-vocabulary.org/#timeRange'), RDF::URI('http://www.w3.org/2000/01/rdf-schema#subClassOf'), RDF::URI('http://www.w3.org/1999/02/22-rdf-syntax-ns#Resource'), :context => RDF::URI('http://rdf.data-vocabulary.org/#')),
    RDF::Statement.new(RDF::URI('http://rdf.data-vocabulary.org/#nutrition'), RDF::URI('http://www.w3.org/2000/01/rdf-schema#subClassOf'), RDF::URI('http://www.w3.org/1999/02/22-rdf-syntax-ns#Resource'), :context => RDF::URI('http://rdf.data-vocabulary.org/#')),
    RDF::Statement.new(RDF::URI('http://rdf.data-vocabulary.org/#instructions'), RDF::URI('http://www.w3.org/2000/01/rdf-schema#subClassOf'), RDF::URI('http://www.w3.org/1999/02/22-rdf-syntax-ns#Resource'), :context => RDF::URI('http://rdf.data-vocabulary.org/#')),
    RDF::Statement.new(RDF::URI('http://rdf.data-vocabulary.org/#ingredient'), RDF::URI('http://www.w3.org/2000/01/rdf-schema#subClassOf'), RDF::URI('http://www.w3.org/1999/02/22-rdf-syntax-ns#Resource'), :context => RDF::URI('http://rdf.data-vocabulary.org/#')),
  ].each {|st| COOKED_VOCAB_STATEMENTS << st }
end
