# This workflow runs continuous CI across different versions of ruby on all branches and pull requests to develop.

name: CI
on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  tests:
    name: Ruby ${{ matrix.ruby }} ${{ matrix.gemfile }}
    if: "contains(github.event.commits[0].message, '[ci skip]') == false"
    runs-on: ubuntu-latest
    env:
      CI: true
      BUNDLE_GEMFILE: "${{ matrix.gemfile }}"
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - 2.4
          - 2.5
          - 2.6
          - 2.7
          #- ruby-head # Until net-http-persistent updated
          #- jruby # No Nokogumbo on JRuby
        gemfile:
          - Gemfile
          - Gemfile-pure
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Install dependencies
        run: bundle install --jobs 4 --retry 3
      - name: Run tests
        run: bundle exec rspec spec
 
